config/routes.rb
Rails.application.routes.draw do
  root to: 'players#index'
  get 'ui(/:action)', controller: 'ui'

  post '/players/generate_lineup', to: 'players#generate_lineup'
  resources :players, only: [:index]
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :projections, foreign_key: "player_id"

  def self.refresh_data
    Player.populate_data if Player.any_refresh?
  end

  def refresh?
    updated_at && updated_at > 60.minutes.ago ? false : true
  end

  private
  def self.populate_data
    ActiveRecord::Base.transaction do
      Player.delete_all #reset all

      inserts = []
      FFNerd.players.each do |player|
        inserts.push "('#{player.display_name.gsub("'","`")}','#{player.player_id}',
                       '#{player.player_id}','#{player.position}','#{player.team}',
                       '#{Time.now.utc}','#{Time.now.utc}')"
      end

      if inserts.any?
        conn = ActiveRecord::Base.connection
        sql = "INSERT INTO players (name, player_id, id, position,
              team, created_at, updated_at) VALUES #{inserts.join(",")}"
        conn.execute sql
      end
    end
  end

  def self.any_refresh?
    Player.all.each do |player|
      return true if player.refresh?
    end
    Player.any? ? false : true #refresh if no records
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def generate_lineup
    #Refresh data
    Player.refresh_data
    Game.refresh_data
    Projection.refresh_data(params[:platform])

    #Set lineup vars
    games = params[:games].map { |game| game.split(" @ ") }.flatten if params[:games]
    lineup_ids = Projection.optimal_lineup(params[:platform], params[:week], params[:type], games)
    @lineup = Projection.format_lineup(lineup_ids, params[:platform], params[:week])

    #Setup instance vars for the view
    @proj_total = 0; @min_total = 0; @max_total = 0; @salary_total = 0
    @platform = params[:platform]
    @lineup.each do |player|
      @proj_total += player[:projection].average
      @max_total += player[:projection].max
      @min_total += player[:projection].min
      @salary_total += player[:projection].salary
    end

    render :index
  end

  def index
  end
end

app/views/players/index.html.haml
%section.main_page
  .row
    .col-md-4.col-md-offset-1.padding-left
      = form_tag(players_generate_lineup_path, method: :post) do
        .row
          .col-xs-12
            %h1.title Optimize Lineup
            %hr
        .row
          .col-xs-9
            %fieldset.form-group
              %label(for="week") Week
              =select_tag :week, options_for_select([9,10,11,12,13,14,15,16,17], params[:week] ? params[:week] : 10), class: "form-control"
        .row
          .col-xs-9
            %fieldset.form-group
              %label(for="type") Lineup Type
              =select_tag :type, options_for_select(["optimal","ceiling","floor"], params[:type]), class: "form-control"
        .row.platform-choice
          .col-xs-12
            %label.radio-inline
              = radio_button_tag :platform, :fanduel, params[:platform] ? (params[:platform] == "fanduel") : true
              Fanduel
            %label.radio-inline
              = radio_button_tag :platform, :draftkings, (params[:platform] == "draftkings")
              Draftkings
            %label.radio-inline
              = radio_button_tag :platform, :yahoo, (params[:platform] == "yahoo")
              Yahoo
        - Game.games_this_week.each do |all_games|
          .row
            .col-xs-12
              %h5="Games - #{all_games.first}"
          .row
            - all_games.second.each do |game|
              .col-xs-5.col-xs-offset-1
                .checkbox
                  =check_box_tag("games[]", game, params[:games] ? params[:games].include?(game) : true, id: "games_#{game}")
                  %label(for="games_#{game}")=game
        .row.btn-row
          .col-md-4
            =button_to "Get Lineup", players_generate_lineup_path, class: "btn btn-primary"
    .col-md-6.padding-left
      - if @lineup
        %h2= "#{@platform.capitalize} Optimal Lineup"
        %br
        %table.table
          %thead.thead-inverse
            %tr
              %th Pos
              %th Player
              %th Projection
              %th Floor
              %th Ceiling
              %th Team
              %th Salary
          %tbody
            - @lineup.each do |player|
              %tr
                %td= player[:position]
                %td= player[:name]
                %td= player[:projection].average
                %td= player[:projection].min
                %td= player[:projection].max
                %td= player[:team]
                %td= number_to_currency(player[:projection].salary, precision: 0)
            %tr
              %td Total
              %td
              %td= number_with_precision(@proj_total, precision: 2)
              %td= number_with_precision(@min_total, precision: 2)
              %td= number_with_precision(@max_total, precision: 2)
              %td
              %td= number_to_currency(@salary_total, precision: 0)
      - else
        %h3 How does this work?
        %br
        %p Using the projections from FantasyFootballNerd.com, this tool will generate the best possible lineup for each of the three main Daily Fantasy Football sites. Just choose from the week/site and hit 'Get Lineup.' The projections will then be placed through a linear programming optimization process to obtain the best possible lineup given the salary constraints of the DFS site.
        %p You can also uncheck games to remove players from those games from consideration. The games displayed will be for the upcoming week's games only (resetting after Monday).
        %p Note - FantasyFootballNerd only has data for upcoming weeks starting around Wednesday of that week.

app/views/players/show.html.haml
%section.main_page
  .row
    .col-md-4.col-md-offset-1
      /
        .row.top-row
          .col-md-12
            %p= "Data Freshness: #{time_ago_in_words Projection.freshness if Projection.freshness} old."
      = form_tag(players_generate_lineup_path, method: :post) do
        .row
          .col-md-12
            %h1.title Optimize Lineup
            %hr
        .row
        /
          .col-xs-12
            .form-group.row
              = label_tag "input1", "Input Num 1", class: "col-sm-4 form-control-label"
              .col-sm-8
                = text_field_tag "input3", nil, placeholder: 'options...', class: "form-control"
            .form-group.row
              = label_tag "input2", "Input Num 2", class: "col-sm-4 form-control-label"
              .col-sm-8
                = text_field_tag "input3", nil, placeholder: 'options...', class: "form-control"
            .form-group.row
              = label_tag "input3", "Input Num 3", class: "col-sm-4 form-control-label"
              .col-sm-8
                = text_field_tag "input3", nil, placeholder: 'options...', class: "form-control"
        .row
          .col-md-12
            %fieldset.form-group
              %label(for="week") Week
              =select_tag :week, options_for_select([9,10,11,12,13,14,15,16,17]), class: "form-control"
        .row
          .col-md-12
            %fieldset.form-group
              %label(for="type") Lineup Type
              =select_tag :type, options_for_select(["optimal","ceiling","floor"]), class: "form-control"
        .row
          .col-md-12
            %label.radio-inline
              = radio_button_tag :platform, :fanduel, true
              Fanduel
            %label.radio-inline
              = radio_button_tag :platform, :draftkings
              Draftkings
            %label.radio-inline
              = radio_button_tag :platform, :yahoo
              Yahoo
        .row.btn-row
          .col-md-4
            =button_to "Get Lineup", players_generate_lineup_path, class: "btn btn-success"
    .col-md-6
      - if @lineup
        %h2= "#{@platform.capitalize} Optimal Lineup"
        %br
        %table.table
          %thead.thead-inverse
            %tr
              %th Pos
              %th Player
              %th Projection
              %th Floor
              %th Ceiling
              %th Team
              %th Salary
          %tbody
            - @lineup.each do |player|
              %tr
                %td= player[:position]
                %td= player[:name]
                %td= player[:projection].average
                %td= player[:projection].min
                %td= player[:projection].max
                %td= player[:team]
                %td= number_to_currency(player[:projection].salary, precision: 0)
            %tr
              %td Total
              %td
              %td= number_with_precision(@proj_total, precision: 2)
              %td= number_with_precision(@min_total, precision: 2)
              %td= number_with_precision(@max_total, precision: 2)
              %td
              %td= number_to_currency(@salary_total, precision: 0)
      - else
        %h3 How does this work?
        %br
        %p Using the projections from FantasyFootballNerd.com, this tool will generate the best possible lineup for each of the three main Daily Fantasy Football sites. Just choose from the week/site and hit 'Get Lineup.' The projections will then be placed through a linear programming optimization process to obtain the best possible lineup given the salary constraints of the DFS site.
        %p Note - FantasyFootballNerd only has data for upcoming weeks starting around Wednesday of that week. 